//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMVCFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBFinal7Entities : DbContext
    {
        public DBFinal7Entities()
            : base("name=DBFinal7Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Card> Card { get; set; }
        public virtual DbSet<Contains> Contains { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Owns> Owns { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
    }
}
