//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMVCFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Owns = new HashSet<Owns>();
            this.Transaction = new HashSet<Transaction>();
        }
    
        
        [Required]
        public int mId { get; set; }

        [Required]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "最少需要三個字'")]
        public string name { get; set; }

        [Required]
        public Nullable<bool> sex { get; set; }


        

        [DisplayFormat(ApplyFormatInEditMode = true , DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> birthday { get; set; }


        [Required]
        [RegularExpression(@"^09\d{2}\-?\d{3}\-?\d{3}$", ErrorMessage = "須為09xx-xxx-xxx")]
        public string phone { get; set; }

        [Required(ErrorMessage = "請輸入email格式")]
        [DataType(DataType.EmailAddress)]
        
        public string email { get; set; }

        [Required(ErrorMessage = "必須輸入6~10位數密碼")]
        [StringLength(12, MinimumLength = 6, ErrorMessage = "請介於6~12位數之間")]
        public string password { get; set; }
        public bool isManager { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Owns> Owns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transaction { get; set; }
    }
}
